#!/usr/bin/env node
// Auto-generated by LLM Wiki — Quartz CI Build Script
// DO NOT EDIT MANUALLY — changes will be overwritten on next publish.
//
// This script runs inside GitHub Actions to:
//   1. Clone Quartz 4.0
//   2. Generate quartz.config.ts from site-config.json
//   3. Copy wiki/ content & adapt frontmatter
//   4. Generate timeline page
//   5. Inject ChatWidget (if enabled)
//   6. Build the static site

import { execSync } from 'node:child_process'
import {
  readFileSync, writeFileSync, mkdirSync, existsSync,
  readdirSync, statSync, rmSync, copyFileSync,
} from 'node:fs'
import { join, basename, relative } from 'node:path'

const REPO_ROOT = process.cwd()

const TYPE_COLORS = {
  entity: '#60a5fa', concept: '#c084fc', source: '#fb923c',
  event: '#f472b6', query: '#4ade80', synthesis: '#f87171',
  overview: '#facc15', comparison: '#2dd4bf', other: '#94a3b8',
}
const CONFIG_PATH = join(REPO_ROOT, '.github/site-config.json')

if (!existsSync(CONFIG_PATH)) {
  console.error('Missing .github/site-config.json — run Publish from LLM Wiki first.')
  process.exit(1)
}

const config = JSON.parse(readFileSync(CONFIG_PATH, 'utf8'))

console.log('=== LLM Wiki — Quartz Site Build ===')
console.log(`Site: ${config.siteTitle}`)
console.log(`Mobile Chat: ${config.enableMobileChat ? 'enabled' : 'disabled'}`)

// ── Step 1: Clone Quartz ────────────────────────────────────────────────
console.log('\n[1/7] Cloning Quartz...')
const quartzDir = join(REPO_ROOT, 'quartz-site')
if (existsSync(quartzDir)) rmSync(quartzDir, { recursive: true, force: true })
execSync('git clone --depth 1 --branch v4.5.2 https://github.com/jackyzha0/quartz.git quartz-site', {
  stdio: 'pipe', cwd: REPO_ROOT,
})
console.log('Installing dependencies...')
execSync('npm ci', { stdio: 'pipe', cwd: quartzDir })

// ── Step 1b: Patch Quartz for fault tolerance ────────────────────────────
console.log('Patching Quartz for fault tolerance...')
patchQuartzFaultTolerance(quartzDir)

// ── Step 2: Generate quartz.config.ts ───────────────────────────────────
console.log('\n[2/7] Generating quartz.config.ts...')
writeFileSync(join(quartzDir, 'quartz.config.ts'), generateQuartzConfig(config))

// ── Step 3: Copy wiki content ───────────────────────────────────────────
console.log('\n[3/7] Copying wiki content...')
const contentDir = join(quartzDir, 'content')
rmSync(contentDir, { recursive: true, force: true })
mkdirSync(contentDir, { recursive: true })
copyDirRecursive(join(REPO_ROOT, 'wiki'), contentDir)

// ── Step 4: Adapt frontmatter ───────────────────────────────────────────
console.log('\n[4/7] Adapting frontmatter...')
const adaptedCount = adaptAllFrontmatter(contentDir)
console.log(`  Adapted ${adaptedCount} files`)

// ── Step 5: Generate timeline ───────────────────────────────────────────
console.log('\n[5/7] Generating timeline page...')
const timelineCount = generateTimeline(contentDir)
if (timelineCount > 0) console.log(`  Generated ${timelineCount} timeline entries`)
else console.log('  No timeline entries found')

// ── Step 6: Inject ChatWidget ───────────────────────────────────────────
if (config.enableMobileChat) {
  console.log('\n[6/7] Injecting ChatWidget...')
  injectChatWidget(config, quartzDir, REPO_ROOT)
} else {
  console.log('\n[6/7] ChatWidget disabled, skipping...')
}

// ── Step 7: Build ───────────────────────────────────────────────────────
console.log('\n[7/7] Building Quartz site...')
execSync('npx quartz build', { stdio: 'inherit', cwd: quartzDir })

// ── Post-build ──────────────────────────────────────────────────────────
const publicDir = join(quartzDir, 'public')
writeFileSync(join(publicDir, '.nojekyll'), '')
writeFileSync(join(publicDir, '404.html'), `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<script>
var p=window.location.pathname;
if(p&&!p.endsWith('/')&&!p.match(/\\.\\w+$/)){window.location.replace(p+'.html')}
</script>
</head><body></body></html>`)

console.log('\n✅ Build complete!')

// ════════════════════════════════════════════════════════════════════════
// Helper functions
// ════════════════════════════════════════════════════════════════════════

function copyDirRecursive(src, dest) {
  mkdirSync(dest, { recursive: true })
  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry)
    const destPath = join(dest, entry)
    if (statSync(srcPath).isDirectory()) {
      copyDirRecursive(srcPath, destPath)
    } else {
      copyFileSync(srcPath, destPath)
    }
  }
}

function walkDir(dir, ext = '.md') {
  const results = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name)
    if (entry.isDirectory()) {
      results.push(...walkDir(fullPath, ext))
    } else if (entry.name.endsWith(ext) && entry.name !== 'log.md') {
      results.push(fullPath)
    }
  }
  return results
}

// ── Frontmatter adaptation (ported from frontmatter-adapter.ts) ─────────

function adaptAllFrontmatter(dir) {
  const files = walkDir(dir)
  const today = new Date().toISOString().split('T')[0]
  let count = 0
  for (const file of files) {
    const content = readFileSync(file, 'utf8')
    const adapted = adaptFrontmatterPure(content, today)
    if (adapted !== content) {
      writeFileSync(file, adapted)
      count++
    }
  }
  return count
}

function adaptFrontmatterPure(content, dateStr) {
  const fmMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (!fmMatch) return content

  let frontmatter = fmMatch[1]
  const body = content.slice(fmMatch[0].length)

  // type → tags
  const typeMatch = frontmatter.match(/^type:\s*["']?(.+?)["']?\s*$/m)
  if (typeMatch) {
    const pageType = typeMatch[1].trim()
    const tagsKeyExists = /^tags:/m.test(frontmatter)
    if (tagsKeyExists) {
      const blockMatch = frontmatter.match(/^tags:\s*\n((?:[ \t]+-.+\n?)*)/m)
      if (blockMatch) {
        if (!blockMatch[1].includes(pageType)) {
          frontmatter = frontmatter.replace(
            /^(tags:\s*\n(?:[ \t]+-.+\n?)*)/m,
            `$1  - ${pageType}\n`,
          )
        }
      } else {
        const inlineMatch = frontmatter.match(/^tags:\s*\[(.*)\]\s*$/m)
        if (inlineMatch) {
          const existing = inlineMatch[1]
          const existingItems = existing.split(',').map((t) => t.trim().replace(/["']/g, '')).filter(Boolean)
          const quotedItems = existingItems.map((t) => `"${t}"`)
          if (!existingItems.includes(pageType)) quotedItems.push(`"${pageType}"`)
          frontmatter = frontmatter.replace(
            /^tags:\s*\[.*\]\s*$/m,
            `tags: [${quotedItems.join(', ')}]`,
          )
        }
      }
    } else {
      frontmatter += `\ntags:\n  - ${pageType}`
    }
  }

  // Re-quote scalar & array fields
  frontmatter = requoteScalar(frontmatter, 'title')
  frontmatter = requoteInlineArray(frontmatter, 'related')

  // date
  if (!frontmatter.includes('date:')) {
    frontmatter += `\ndate: ${dateStr}`
  }

  return `---\n${frontmatter}\n---${body}`
}

function yamlQuote(value) {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

function requoteScalar(frontmatter, field) {
  const re = new RegExp(`^(${field}:\\s*)(.+)$`, 'm')
  const match = frontmatter.match(re)
  if (!match) return frontmatter
  const raw = match[2].trim()
  if (/^"[^"\\]*(?:\\.[^"\\]*)*"$/s.test(raw)) return frontmatter
  if (/^'[^']*'$/s.test(raw)) return frontmatter
  const stripped = raw.replace(/^["']|["']$/g, '')
  return frontmatter.replace(re, `${match[1]}${yamlQuote(stripped)}`)
}

function requoteInlineArray(frontmatter, field) {
  const re = new RegExp(`^(${field}:\\s*)\\[(.+)\\]\\s*$`, 'm')
  const match = frontmatter.match(re)
  if (!match) return frontmatter
  const items = match[2].split(',').map((t) => t.trim().replace(/^["']|["']$/g, '')).filter(Boolean)
  const quoted = items.map((t) => yamlQuote(t))
  return frontmatter.replace(re, `${match[1]}[${quoted.join(', ')}]`)
}

// ── Timeline generation (ported from frontmatter-adapter.ts) ────────────

function extractFmOriginDate(content) {
  const m = content.match(/^---\r?\n[\s\S]*?^origin_date:\s*["']?(.+?)["']?\s*$/m)
  return m ? m[1].trim() : null
}

function extractFmTitle(content, fallback) {
  const m = content.match(/^---\r?\n[\s\S]*?^title:\s*["']?(.+?)["']?\s*$/m)
  return m ? m[1].trim() : fallback.replace(/\.md$/, '').replace(/-/g, ' ')
}

function extractFmType(content) {
  const m = content.match(/^---\r?\n[\s\S]*?^type:\s*["']?(.+?)["']?\s*$/m)
  return m ? m[1].trim().toLowerCase() : 'other'
}

function extractFmArrayField(content, field) {
  const m = content.match(new RegExp(`^${field}:\\s*\\[(.+?)\\]`, 'm'))
  if (!m) return []
  return m[1].split(',').map((s) => s.trim().replace(/["']/g, '')).filter(Boolean)
}

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

function generateTimeline(contentDir) {
  const files = walkDir(contentDir)
  const entries = []
  const slugToLabel = new Map()
  const relations = []

  for (const file of files) {
    const content = readFileSync(file, 'utf8')
    const relPath = relative(contentDir, file).replace(/\\/g, '/')
    const slug = relPath.replace(/\.md$/, '')
    const title = extractFmTitle(content, basename(file))
    const type = extractFmType(content)
    const date = extractFmOriginDate(content)

    slugToLabel.set(slug, title)
    if (date) entries.push({ date, label: title, type, slug })

    for (const cause of extractFmArrayField(content, 'causes')) {
      relations.push({ source: cause, target: slug, type: 'causes' })
    }
    for (const effect of extractFmArrayField(content, 'effects')) {
      relations.push({ source: slug, target: effect, type: 'causes' })
    }
  }

  if (entries.length === 0) return 0

  entries.sort((a, b) => a.date.localeCompare(b.date))

  const eventEntries = entries.filter((e) => e.type === 'event')
  const conceptEntries = entries.filter((e) => e.type === 'concept' || e.type === 'entity')

  const totalCount = entries.length
  const eventCount = eventEntries.length
  const conceptCount = conceptEntries.length

  writeFileSync(join(contentDir, 'timeline.md'),
    buildTimelineHtml('Timeline', 'timeline', entries, totalCount, eventCount, conceptCount, relations, slugToLabel))
  writeFileSync(join(contentDir, 'timeline-events.md'),
    buildTimelineHtml('Timeline — Events', 'timeline-events', eventEntries, totalCount, eventCount, conceptCount, relations, slugToLabel))
  writeFileSync(join(contentDir, 'timeline-concepts.md'),
    buildTimelineHtml('Timeline — Concepts & Entities', 'timeline-concepts', conceptEntries, totalCount, eventCount, conceptCount, relations, slugToLabel))

  return totalCount
}

function buildTimelineHtml(title, pageSlug, entries, totalCount, eventCount, conceptCount, relations, slugToLabel) {
  let currentYear = ''
  const entriesHtml = entries.map((e, i) => {
    const year = e.date.slice(0, 4)
    const showYear = year !== currentYear
    currentYear = year
    const color = TYPE_COLORS[e.type] ?? TYPE_COLORS.other
    const dateHtml = showYear
      ? `<span class="tl-date-year">${escapeHtml(e.date)}</span>`
      : `<span>${escapeHtml(e.date.slice(5))}</span>`
    return `<div class="tl-entry" data-idx="${i}">
  <div class="tl-date">${dateHtml}</div>
  <div class="tl-mobile-date">${escapeHtml(e.date)}</div>
  <div class="tl-dot" style="background:${color}"></div>
  <div class="tl-card">
    <a href="/${e.slug}">
      <div class="tl-card-type"><span class="tl-card-dot" style="background:${color}"></span> ${escapeHtml(e.type)}</div>
      <div class="tl-card-title">${escapeHtml(e.label)}</div>
    </a>
  </div>
</div>`
  }).join('\n')

  let relationsHtml = ''
  if (relations.length > 0) {
    const items = relations.map((r) => {
      const src = escapeHtml(slugToLabel.get(r.source) ?? r.source)
      const tgt = escapeHtml(slugToLabel.get(r.target) ?? r.target)
      return `<div class="tl-rel">
  <span class="tl-rel-name">${src}</span>
  <span class="tl-rel-type">${escapeHtml(r.type)}</span>
  <span class="tl-rel-name">${tgt}</span>
</div>`
    }).join('\n')
    relationsHtml = `<div class="tl-relations">
<h3>Causal &amp; Temporal Relations (${relations.length})</h3>
${items}
</div>`
  }

  const tabHtml = `<div class="tl-tabs">
<a class="tl-tab${pageSlug === 'timeline' ? ' active' : ''}" href="/timeline">All (${totalCount})</a>
<a class="tl-tab${pageSlug === 'timeline-events' ? ' active' : ''}" href="/timeline-events">Events (${eventCount})</a>
<a class="tl-tab${pageSlug === 'timeline-concepts' ? ' active' : ''}" href="/timeline-concepts">Concepts &amp; Entities (${conceptCount})</a>
</div>`

  return `---
title: ${title}
date: ${new Date().toISOString().split('T')[0]}
---

<style>
.tl-tabs { display: flex; gap: 8px; max-width: 720px; margin: 0 auto 1.5rem; flex-wrap: wrap; }
.tl-tab { padding: 6px 14px; border: 1px solid #e5e5e5; border-radius: 20px; font-size: 0.8rem; text-decoration: none; color: #555; transition: all 0.15s; }
.tl-tab:hover { border-color: #999; color: #222; }
.tl-tab.active { background: #284b63; color: #fff; border-color: #284b63; }
.tl-container { max-width: 720px; margin: 2rem auto; position: relative; padding-left: 140px; }
.tl-line { position: absolute; left: 126px; top: 0; bottom: 0; width: 2px; background: #e5e5e5; }
.tl-entry { position: relative; display: flex; align-items: flex-start; gap: 12px; padding-bottom: 1.5rem; }
.tl-date { position: absolute; left: -140px; width: 120px; text-align: right; padding-right: 16px; padding-top: 4px; font-size: 0.8rem; color: #888; }
.tl-date-year { font-weight: 600; color: #333; font-size: 0.85rem; }
.tl-mobile-date { display: none; font-size: 0.7rem; color: #888; margin-bottom: 2px; }
.tl-dot { position: absolute; left: -8px; top: 6px; width: 14px; height: 14px; border-radius: 50%; border: 2px solid #fff; box-shadow: 0 0 0 1px rgba(0,0,0,0.08); flex-shrink: 0; }
.tl-card { flex: 1; border: 1px solid #e5e5e5; border-radius: 8px; padding: 0.75rem 1rem; transition: background-color 0.15s; }
.tl-card:hover { background-color: rgba(0,0,0,0.02); }
.tl-card a { text-decoration: none; color: inherit; }
.tl-card-type { display: inline-flex; align-items: center; gap: 4px; font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.03em; color: #888; margin-bottom: 2px; }
.tl-card-dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; }
.tl-card-title { font-size: 0.9rem; font-weight: 500; color: #222; }
.tl-pager { display: flex; justify-content: center; align-items: center; gap: 6px; margin: 1.5rem 0; flex-wrap: wrap; }
.tl-pager button { padding: 6px 12px; border: 1px solid #e5e5e5; border-radius: 6px; background: #fff; cursor: pointer; font-size: 0.8rem; color: #333; transition: all 0.15s; }
.tl-pager button:hover { border-color: #999; }
.tl-pager button.active { background: #284b63; color: #fff; border-color: #284b63; }
.tl-pager button:disabled { opacity: 0.4; cursor: default; }
.tl-relations { margin-top: 2rem; border-top: 1px solid #e5e5e5; padding-top: 1.5rem; }
.tl-relations h3 { font-size: 0.85rem; font-weight: 600; margin-bottom: 0.75rem; color: #555; }
.tl-rel { display: flex; align-items: center; gap: 8px; font-size: 0.8rem; padding: 0.4rem 0.6rem; border: 1px solid #e5e5e5; border-radius: 6px; margin-bottom: 0.4rem; }
.tl-rel-name { font-weight: 500; color: #333; }
.tl-rel-type { font-size: 0.65rem; background: #f3f3f3; padding: 2px 6px; border-radius: 4px; color: #777; white-space: nowrap; }
@media (max-width: 640px) {
  .tl-container { padding-left: 0; }
  .tl-line { left: 14px; }
  .tl-date { display: none; }
  .tl-mobile-date { display: block; }
  .tl-dot { left: 8px; }
  .tl-entry { padding-left: 36px; }
  .tl-tab { padding: 5px 10px; font-size: 0.75rem; }
}
@media (prefers-color-scheme: dark) {
  .tl-tab { border-color: #333; color: #aaa; }
  .tl-tab:hover { border-color: #666; color: #ddd; }
  .tl-tab.active { background: #284b63; color: #fff; border-color: #284b63; }
  .tl-line { background: #333; }
  .tl-date { color: #888; }
  .tl-date-year { color: #ddd; }
  .tl-dot { border-color: #1a1a1a; }
  .tl-card { border-color: #333; }
  .tl-card:hover { background-color: rgba(255,255,255,0.04); }
  .tl-card-title { color: #eee; }
  .tl-pager button { background: #1e1e21; border-color: #333; color: #ccc; }
  .tl-pager button:hover { border-color: #666; }
  .tl-pager button.active { background: #284b63; color: #fff; border-color: #284b63; }
  .tl-rel { border-color: #333; }
  .tl-rel-name { color: #ddd; }
  .tl-rel-type { background: #2a2a2a; color: #aaa; }
  .tl-relations h3 { color: #aaa; }
}
</style>

${tabHtml}

<div class="tl-container">
<div class="tl-line"></div>
${entriesHtml}
</div>
<div class="tl-pager" id="tl-pager"></div>
${relationsHtml}

<script>
;(function(){
  var PER=30,entries=document.querySelectorAll('.tl-entry'),total=entries.length,pager=document.getElementById('tl-pager');
  if(!pager||total<=PER)return;
  var pages=Math.ceil(total/PER);
  function show(p){
    p=Math.max(1,Math.min(pages,p));
    for(var i=0;i<total;i++)entries[i].style.display=(i>=(p-1)*PER&&i<p*PER)?'':'none';
    location.hash='page-'+p;
    render(p);
  }
  function render(p){
    var h='<button'+(p<=1?' disabled':'')+' onclick="window._tlGo('+(p-1)+')">&laquo;</button>';
    var start=Math.max(1,p-2),end=Math.min(pages,p+2);
    if(start>1)h+='<button onclick="window._tlGo(1)">1</button>';
    if(start>2)h+='<span style="padding:0 4px;color:#888">...</span>';
    for(var i=start;i<=end;i++)h+='<button class="'+(i===p?'active':'')+'" onclick="window._tlGo('+i+')">'+i+'</button>';
    if(end<pages-1)h+='<span style="padding:0 4px;color:#888">...</span>';
    if(end<pages)h+='<button onclick="window._tlGo('+pages+')">'+pages+'</button>';
    h+='<button'+(p>=pages?' disabled':'')+' onclick="window._tlGo('+(p+1)+')">&raquo;</button>';
    pager.innerHTML=h;
  }
  window._tlGo=show;
  var m=(location.hash||'').match(/page-(\d+)/);
  show(m?parseInt(m[1]):1);
  window.addEventListener('hashchange',function(){var m=(location.hash||'').match(/page-(\d+)/);if(m)show(parseInt(m[1]));});
})();
</script>
`
}

// ── Quartz config generation (ported from quartz-config.ts) ─────────────

function generateQuartzConfig(cfg) {
  const locale = cfg.locale === 'zh-CN' ? 'zh-CN' : 'en-US'
  const ignorePatterns = JSON.stringify(['.obsidian/**', '.llm-wiki/**', 'raw/**', ...(cfg.ignorePatterns || [])])
  const headerFont = cfg.locale === 'zh-CN' ? 'Noto Sans SC' : 'Scholar'
  const bodyFont = headerFont

  // Auto-generate baseUrl from githubRepo if not explicitly set
  let baseUrl = cfg.baseUrl || ''
  if (!baseUrl && cfg.githubRepo) {
    const [owner, repo] = cfg.githubRepo.split('/')
    if (owner && repo) {
      baseUrl = repo === `${owner}.github.io`
        ? `https://${owner}.github.io`
        : `https://${owner}.github.io/${repo}`
    }
  }

  const mobileImports = cfg.enableMobileChat
    ? `\nimport ChatWidget from "./quartz/components/custom/ChatWidget"`
    : ''

  return `import { QuartzConfig } from "./quartz"
import * as Plugin from "./quartz/plugins"${mobileImports}

const config: QuartzConfig = {
  configuration: {
    pageTitle: ${JSON.stringify(cfg.siteTitle)},
    enableSPA: ${cfg.enableSPA !== false},
    enablePopovers: true,
    locale: "${locale}",
    baseUrl: ${JSON.stringify(baseUrl)},
    ignorePatterns: ${ignorePatterns},
    defaultDateType: "modified",
    theme: {
      fontOrigin: "googleFonts",
      typography: {
        header: ${JSON.stringify(headerFont)},
        body: ${JSON.stringify(bodyFont)},
        code: "JetBrains Mono",
      },
      colors: {
        lightMode: {
          light: "#faf8f8", lightgray: "#e5e5e5", gray: "#b8b8b8",
          darkgray: "#4e4e4e", dark: "#2b2b2b", secondary: "#284b63",
          tertiary: "#84a98c", highlight: "rgba(143, 159, 169, 0.15)",
        },
        darkMode: {
          light: "#1e1e21", lightgray: "#292629", gray: "#4e4e4e",
          darkgray: "#b8b8b8", dark: "#eae8e8", secondary: "#7b97aa",
          tertiary: "#84a98c", highlight: "rgba(143, 159, 169, 0.15)",
        },
      },
    },
  },
  plugins: {
    transformers: [
      Plugin.FrontMatter(),
      Plugin.TableOfContents(),
      Plugin.CreatedModifiedDate({ priority: ["frontmatter", "filesystem"] }),
      Plugin.Latex({ renderEngine: "katex" }),
      Plugin.SyntaxHighlighting(),
      Plugin.ObsidianFlavoredMarkdown(),
      Plugin.GitHubFlavoredMarkdown(),
      Plugin.CrawlLinks({ markdownLinkResolution: "shortest" }),
      Plugin.Description(),
    ],
    filters: [Plugin.RemoveDrafts()],
    emitters: [
      Plugin.AliasRedirects(),
      Plugin.ComponentResources(),
      Plugin.ContentIndex({ enableSiteMap: ${cfg.enableRSS !== false}, enableRSS: ${cfg.enableRSS !== false} }),
      Plugin.FolderPage(),
      Plugin.TagPage(),

      Plugin.ContentPage(),
      Plugin.Assets(),
      Plugin.Static(),
      Plugin.NotFoundPage(),
    ],
  },
}

export default config
`
}

// ── ChatWidget injection ────────────────────────────────────────────────

function injectChatWidget(cfg, quartzDir, repoRoot) {
  const customDir = join(quartzDir, 'quartz', 'components', 'custom')
  mkdirSync(customDir, { recursive: true })
  mkdirSync(join(customDir, 'styles'), { recursive: true })
  mkdirSync(join(customDir, 'scripts'), { recursive: true })

  const srcDir = join(repoRoot, '.github', 'quartz-components')
  if (!existsSync(srcDir)) {
    console.warn('  ChatWidget source files not found in .github/quartz-components/ — skipping')
    return
  }

  // Copy component files, fixing import path for Quartz directory structure
  const tsx = readFileSync(join(srcDir, 'ChatWidget.tsx'), 'utf8')
  const fixedTsx = tsx.replace(/from "\.\/types"/, 'from "../types"')
  writeFileSync(join(customDir, 'ChatWidget.tsx'), fixedTsx)

  const scssSrc = join(srcDir, 'styles', 'chat-widget.scss')
  if (existsSync(scssSrc)) {
    copyFileSync(scssSrc, join(customDir, 'styles', 'chat-widget.scss'))
  }

  // Copy and configure inline script with runtime config preamble
  const inlineSrc = join(srcDir, 'scripts', 'chat-widget.inline.ts')
  if (existsSync(inlineSrc)) {
    const inline = readFileSync(inlineSrc, 'utf8')
    const configObj = {}
    if (cfg.githubRepo) configObj.githubRepo = cfg.githubRepo
    const preamble = `window.__LLM_WIKI_CONFIG = ${JSON.stringify(configObj)};\n`
    writeFileSync(join(customDir, 'scripts', 'chat-widget.inline.ts'), preamble + inline)
  }

  // Modify quartz.layout.ts to register ChatWidget
  const layoutPath = join(quartzDir, 'quartz.layout.ts')
  let layout = readFileSync(layoutPath, 'utf8')

  if (!layout.includes('ChatWidget')) {
    layout = `import ChatWidget from "./quartz/components/custom/ChatWidget"\n${layout}`
    // Add to sharedPageComponents.afterBody (works with any Quartz layout version)
    layout = layout.replace(
      /afterBody: \[\]/g,
      'afterBody: [ChatWidget()]',
    )
  }
  writeFileSync(layoutPath, layout)
}

// ── Patch Quartz source for fault tolerance ──────────────────────────────

function patchQuartzFaultTolerance(quartzDir) {
  const parsePath = join(quartzDir, 'quartz', 'processors', 'parse.ts')
  let src = readFileSync(parsePath, 'utf8')

  // 1) Per-file catch: replace trace() (which re-throws/exits) with console.warn
  //    Original: trace(`\nFailed to process \`${fp}\``, err as Error)
  const traceMarker = 'Failed to process'
  const traceIdx = src.indexOf(traceMarker)
  if (traceIdx !== -1) {
    // Find the full statement: trace(`...`, err as Error)
    const lineStart = src.lastIndexOf('trace(', traceIdx)
    const lineEnd = src.indexOf(')', traceIdx + traceMarker.length) + 1
    if (lineStart !== -1 && lineEnd > lineStart) {
      const oldLine = src.slice(lineStart, lineEnd)
      const newLine = 'console.warn(`[WARN] Skipping ${fp}: ${(err instanceof Error ? err.message : String(err)).split("\\n")[0]}`)'
      src = src.slice(0, lineStart) + newLine + src.slice(lineEnd)
    }
  }

  // 2) Multi-threaded WorkerPromise.catch: replace process.exit(1) with warning
  src = src.replace(
    /const results: ProcessedContent\[\]\[\] = await WorkerPromise\.all\(childPromises\)\.catch\(\(err\) => \{\s*\n\s*const errString = err\.toString\(\)\.slice\("Error:"\.length\)\s*\n\s*console\.error\(errString\)\s*\n\s*process\.exit\(1\)\s*\n\s*\}\)/,
    `const results: ProcessedContent[][] = await WorkerPromise.all(childPromises).catch((err) => {
      console.warn('[WARN] Some worker threads failed (skipping problematic files):', err?.message || err)
      return []
    })`,
  )

  writeFileSync(parsePath, src)
  console.log('  Patched quartz/processors/parse.ts for fault tolerance')
}
