#!/usr/bin/env node
// Wiki Content Review — calls LLM via Cloudflare Worker proxy, creates GitHub Issue
// Triggered by .github/workflows/wiki-review.yml on push to main (wiki/ changes)

import { execSync } from 'node:child_process'
import { readFileSync, existsSync } from 'node:fs'
import { join, basename } from 'node:path'

const WORKER_URL = 'https://twilight-violet-b5af.zhangpybit.workers.dev'
const MODEL = 'glm-5.1'
const MAX_TOKENS = 225000

// ── Step 1: Get changed wiki files ────────────────────────────────────────
console.log('Getting changed wiki files...')
const before = process.env.PUSH_BEFORE
const sha = process.env.PUSH_SHA

let diffCmd
if (before && sha && before !== '0000000000000000000000000000000000000000') {
  // Use full push range — captures all commits in this push
  console.log(`Push range: ${before.slice(0, 8)}..${sha.slice(0, 8)}`)
  diffCmd = `git diff ${before} ${sha} --name-only -- wiki/`
} else {
  // Fallback for first push or manual trigger
  console.log('Falling back to HEAD~1 (no before SHA available)')
  diffCmd = 'git diff HEAD~1 HEAD --name-only -- wiki/'
}

let changedFiles
try {
  changedFiles = execSync(diffCmd, { encoding: 'utf8' })
    .split('\n').map((l) => l.trim()).filter((l) => l && l.endsWith('.md'))
} catch {
  console.log('No wiki changes detected or first commit — skipping review.')
  process.exit(0)
}

if (changedFiles.length === 0) {
  console.log('No markdown files changed — skipping review.')
  process.exit(0)
}

console.log(`Found ${changedFiles.length} changed files:`)
changedFiles.forEach((f) => console.log(`  - ${f}`))

// ── Step 2: Read file contents ────────────────────────────────────────────
const REPO_ROOT = process.cwd()
const fileContents = []
for (const fp of changedFiles) {
  const fullPath = join(REPO_ROOT, fp)
  if (!existsSync(fullPath)) {
    console.log(`  (deleted, skipping): ${fp}`)
    continue
  }
  const content = readFileSync(fullPath, 'utf8')
  const title = basename(fp, '.md')
  fileContents.push({ path: fp, title, content })
}

if (fileContents.length === 0) {
  console.log('No readable files to review — skipping.')
  process.exit(0)
}

// Truncate individual files to ~3000 chars to stay within context budget
const MAX_FILE_CHARS = 3000
const truncatedFiles = fileContents.map((f) => {
  const trimmed = f.content.length > MAX_FILE_CHARS
    ? f.content.slice(0, MAX_FILE_CHARS) + '\n... (truncated)'
    : f.content
  return `### ${f.title}\nPath: \`${f.path}\`\n\n${trimmed}`
})

const filesBlock = truncatedFiles.join('\n\n---\n\n')

// ── Step 3: Call LLM ──────────────────────────────────────────────────────
console.log('\nCalling LLM for review...')
const systemPrompt = `你是一位 AI/科技领域的研究分析专家。你对用户提供的技术笔记进行深度分析和 Review。请使用 Markdown 格式输出，语言简洁专业。`

const userPrompt = `请对以下最近更新的 wiki 内容进行深度 Review，包括：

1. **内容摘要** — 逐条概述每个更新内容的要点（每个文件一条）
2. **研究趋势分析** — 从这些更新中识别当前 AI 领域的研究趋势和热点方向
3. **拓展建议** — 建议可以进一步深入研究或补充的内容方向
4. **关联发现** — 指出这些内容之间可能存在的关联或交叉点

以下是本次更新的 wiki 内容：

---

${filesBlock}`

const apiEndpoint = `${WORKER_URL.replace(/\/+$/, '')}/v1/messages`

const resp = await fetch(apiEndpoint, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'anthropic-version': '2023-06-01',
  },
  body: JSON.stringify({
    model: MODEL,
    max_tokens: MAX_TOKENS,
    system: systemPrompt,
    messages: [{ role: 'user', content: userPrompt }],
  }),
})

if (!resp.ok) {
  const errText = await resp.text()
  console.error(`LLM API error ${resp.status}: ${errText}`)
  process.exit(1)
}

const data = await resp.json()
const reviewText = data.content?.[0]?.text

if (!reviewText) {
  console.error('LLM returned empty response:', JSON.stringify(data).slice(0, 500))
  process.exit(1)
}

console.log('Review generated successfully.')

// ── Step 4: Create GitHub Issue ───────────────────────────────────────────
const today = new Date().toISOString().split('T')[0]
const fileList = changedFiles.map((f) => `- \`${f}\``).join('\n')

const issueBody = `${reviewText}

---

<details>
<summary>变更文件列表 (${changedFiles.length})</summary>

${fileList}

</details>

---
*Auto-generated by [wiki-review](https://github.com/BITDeeper/llm_wiki_notebook/actions/workflows/wiki-review.yml)*
`

const escapedBody = issueBody.replace(/"/g, '\\"').replace(/`/g, '\\`').replace(/\$/g, '\\$')

const issueTitle = `Wiki Review — ${today}`

console.log('\nCreating GitHub Issue...')
try {
  const result = execSync(
    `gh issue create --title "${issueTitle}" --body "${escapedBody}" --label "wiki-review"`,
    { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] },
  )
  console.log(`Issue created: ${result.trim()}`)
} catch (err) {
  // Label might not exist, try without it
  console.log('Retrying without label...')
  try {
    const result = execSync(
      `gh issue create --title "${issueTitle}" --body "${escapedBody}"`,
      { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] },
    )
    console.log(`Issue created: ${result.trim()}`)
  } catch (err2) {
    console.error('Failed to create issue:', err2.message)
    // Fallback: write review to stdout so it's visible in Actions logs
    console.log('\n--- Review Content ---\n')
    console.log(reviewText)
    process.exit(1)
  }
}
