#!/usr/bin/env node
// Wiki Content Review — uses Claude Code CLI for intelligent wiki review
// Triggered by .github/workflows/wiki-review.yml on push to main (wiki/ changes)

import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'

// ── Step 1: Get changed wiki files ────────────────────────────────────────
console.log('Getting changed wiki files...')
const baseSha = process.env.BASE_SHA
const headSha = process.env.HEAD_SHA

if (!baseSha) {
  console.error('BASE_SHA not set — cannot determine diff range.')
  process.exit(1)
}

console.log(`Review range: ${baseSha}..${headSha}`)
const diffCmd = `git diff ${baseSha} ${headSha} --name-only -- wiki/`

let changedFiles
try {
  changedFiles = execSync(diffCmd, { encoding: 'utf8' })
    .split('\n').map((l) => l.trim()).filter((l) => l && l.endsWith('.md'))
} catch {
  console.log('No wiki changes detected or first commit — skipping review.')
  process.exit(0)
}

if (changedFiles.length === 0) {
  console.log('No markdown files changed — skipping review.')
  process.exit(0)
}

console.log(`Found ${changedFiles.length} changed files:`)
changedFiles.forEach((f) => console.log(`  - ${f}`))

// ── Step 2: Build prompt with file paths only ─────────────────────────────
const fileList = changedFiles.map((f) => `- \`${f}\``).join('\n')

const prompt = `你是一位 AI/科技领域的研究分析专家。你对用户提供的技术笔记进行深度分析和 Review。请使用 Markdown 格式输出，语言简洁专业。

本次更新的 wiki 文件列表：

${fileList}

请先使用 Read 工具逐个读取这些文件的内容，然后进行深度 Review，包括：

1. **内容摘要** — 逐条概述每个更新内容的要点（每个文件一条）
2. **研究趋势分析** — 从这些更新中识别当前 AI 领域的研究趋势和热点方向
3. **拓展建议** — 建议可以进一步深入研究或补充的内容方向
4. **关联发现** — 指出这些内容之间可能存在的关联或交叉点`

// ── Step 3: Call Claude Code CLI ──────────────────────────────────────────
console.log('\nCalling Claude Code CLI...')

let reviewText
try {
  reviewText = execSync(
    `claude -p --effort medium --model glm-4.7 --max-budget-usd 10 --allowedTools Read,Glob,Grep,WebSearch,WebFetch`,
    {
      input: prompt,
      encoding: 'utf8',
      timeout: 1800000, // 30 min timeout
    },
  ).trim()
} catch (err) {
  console.error('Claude CLI failed:', err.message)
  if (err.stdout) {
    reviewText = err.stdout.trim()
  }
  if (!reviewText) {
    console.error('No output captured. Exiting.')
    process.exit(1)
  }
}

console.log('Review generated successfully.')

// ── Step 4: Create GitHub Issue ───────────────────────────────────────────
const today = new Date().toISOString().split('T')[0]

const issueBody = `${reviewText}

---

<details>
<summary>变更文件列表 (${changedFiles.length})</summary>

${fileList}

</details>

---
*Auto-generated by [wiki-review](https://github.com/BITDeeper/llm_wiki_notebook/actions/workflows/wiki-review.yml)*
`

const issueTitle = `Wiki Review — ${today}`

// Write body to temp file to avoid shell escaping issues
const tmpBodyFile = `/tmp/wiki-review-${today}.md`
writeFileSync(tmpBodyFile, issueBody, 'utf8')

console.log('\nCreating GitHub Issue...')
try {
  const result = execSync(
    `gh issue create --title "${issueTitle}" --body-file "${tmpBodyFile}" --label "wiki-review"`,
    { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] },
  )
  console.log(`Issue created: ${result.trim()}`)
} catch (err) {
  // Label might not exist, try without it
  console.log('Retrying without label...')
  try {
    const result = execSync(
      `gh issue create --title "${issueTitle}" --body-file "${tmpBodyFile}"`,
      { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] },
    )
    console.log(`Issue created: ${result.trim()}`)
  } catch (err2) {
    console.error('Failed to create issue:', err2.message)
    // Fallback: write review to stdout so it's visible in Actions logs
    console.log('\n--- Review Content ---\n')
    console.log(reviewText)
    process.exit(1)
  }
}
